gen-mr:
	@read -p "Module Name : " moduleName; \
	ng g m $${moduleName} --routing
gen-m:
	@read -p "Module Name : " moduleName; \
	ng g m $${moduleName}
gen-c:
	@read -p "Component Name : " componentName; \
	ng g c $${componentName}
ui:
	ng serve --open

