/*
 * Inventory
 * API for inventory management
 *
 * OpenAPI spec version: 1.0-snapshot
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.bhuwanupadhyay.inventory.v1.invoker.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
